### ISSUE TITLE
Upgrade to support Django3.2

### ISSUE THREAD

**Issue by ghassanmas** [Benoss/django-elasticsearch-debug-toolbar#16]
Hello, 
Thank you for your valuable contribution. 

Are there going to be an upgrade/support Django3.2 soon? hence #14 

Open-edx is using this pacakge. And given open-edx is in the process of upgrading all dependencies to support Django>3.2  (for [context](https://github.com/edx/upgrades/issues/43))

Let me know if you need to suggest changes (_assuming you are willing to devote some time for review_).

**Comment by Benoss** [comment]
Should be fixed with version 3.0.2
