### ISSUE TITLE
ElasticQueryInfo.__init__ fails in Python 3

### ISSUE THREAD

**Issue by pquentin** [Benoss/django-elasticsearch-debug-toolbar#4]
As you can see in [Transform.perform_request](https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/transport.py#L288-L293) from the Python elasticsearch client, `body` is specifically encoded to `bytes`. However, `full_url` is a Unicode `str`.

```python
    def __init__(self, method, full_url, path, body, status_code, response, duration):
        self.method = method
        self.full_url = full_url
        self.path = path
        self.body = _pretty_json(body)
        self.status_code = status_code
        self.response = _pretty_json(response)
        self.duration = round(duration * 1000, 2)
>       self.hash = hashlib.md5(self.full_url + self.body).hexdigest()
E       TypeError: Can't convert 'bytes' object to str implicitly
```

Since `hashlib.md5()` expects `bytes`, you need to encode `self.full_url` too using `self.full_url.encode('ascii')` since a well formatted URL cannot contain anything else than ASCII.

**Comment by Benoss** [comment]
Good point,
 will try to change this tomorrow, or you can post a create a Pull request if you want to

**Comment by Benoss** [comment]
1.0.3 should fix this

**Comment by pquentin** [comment]
@Benoss Thank you for the fixes!
